//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NAPS2.Lang.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MiscResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MiscResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NAPS2.Lang.Resources.MiscResources", typeof(MiscResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All ({0}).
        /// </summary>
        internal static string AllCount {
            get {
                return ResourceManager.GetString("AllCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when trying to auto save..
        /// </summary>
        internal static string AutoSaveError {
            get {
                return ResourceManager.GetString("AutoSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic Updates.
        /// </summary>
        internal static string AutoUpdates {
            get {
                return ResourceManager.GetString("AutoUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error ocurred during the batch scan..
        /// </summary>
        internal static string BatchError {
            get {
                return ResourceManager.GetString("BatchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch cancelled..
        /// </summary>
        internal static string BatchStatusCancelled {
            get {
                return ResourceManager.GetString("BatchStatusCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelling.....
        /// </summary>
        internal static string BatchStatusCancelling {
            get {
                return ResourceManager.GetString("BatchStatusCancelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch completed successfully..
        /// </summary>
        internal static string BatchStatusComplete {
            get {
                return ResourceManager.GetString("BatchStatusComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch scan stopped due to error..
        /// </summary>
        internal static string BatchStatusError {
            get {
                return ResourceManager.GetString("BatchStatusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning page {0}....
        /// </summary>
        internal static string BatchStatusPage {
            get {
                return ResourceManager.GetString("BatchStatusPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving batch results....
        /// </summary>
        internal static string BatchStatusSaving {
            get {
                return ResourceManager.GetString("BatchStatusSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning page {0} (scan {1})....
        /// </summary>
        internal static string BatchStatusScanPage {
            get {
                return ResourceManager.GetString("BatchStatusScanPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for scan {0}....
        /// </summary>
        internal static string BatchStatusWaitingForScan {
            get {
                return ResourceManager.GetString("BatchStatusWaitingForScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Profile.
        /// </summary>
        internal static string ChooseProfile {
            get {
                return ResourceManager.GetString("ChooseProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to clear {0} item(s)?.
        /// </summary>
        internal static string ConfirmClearItems {
            get {
                return ResourceManager.GetString("ConfirmClearItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete &quot;{0}&quot;?.
        /// </summary>
        internal static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete {0} item(s)?.
        /// </summary>
        internal static string ConfirmDeleteItems {
            get {
                return ResourceManager.GetString("ConfirmDeleteItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete {0} profiles?.
        /// </summary>
        internal static string ConfirmDeleteMultipleProfiles {
            get {
                return ResourceManager.GetString("ConfirmDeleteMultipleProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the profile {0}?.
        /// </summary>
        internal static string ConfirmDeleteSingleProfile {
            get {
                return ResourceManager.GetString("ConfirmDeleteSingleProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file {0} already exists. Do you want to overwrite it?.
        /// </summary>
        internal static string ConfirmOverwriteFile {
            get {
                return ResourceManager.GetString("ConfirmOverwriteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want undo your changes to {0} image(s)?.
        /// </summary>
        internal static string ConfirmResetImages {
            get {
                return ResourceManager.GetString("ConfirmResetImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying....
        /// </summary>
        internal static string Copying {
            get {
                return ResourceManager.GetString("Copying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Progress.
        /// </summary>
        internal static string CopyProgress {
            get {
                return ResourceManager.GetString("CopyProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom ({0}x{1} {2}).
        /// </summary>
        internal static string CustomPageSizeFormat {
            get {
                return ResourceManager.GetString("CustomPageSizeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected scanner is busy..
        /// </summary>
        internal static string DeviceBusy {
            get {
                return ResourceManager.GetString("DeviceBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scanner&apos;s cover is open..
        /// </summary>
        internal static string DeviceCoverOpen {
            get {
                return ResourceManager.GetString("DeviceCoverOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected scanner could not be found..
        /// </summary>
        internal static string DeviceNotFound {
            get {
                return ResourceManager.GetString("DeviceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected scanner is offline..
        /// </summary>
        internal static string DeviceOffline {
            get {
                return ResourceManager.GetString("DeviceOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scanner has a paper jam..
        /// </summary>
        internal static string DevicePaperJam {
            get {
                return ResourceManager.GetString("DevicePaperJam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scanner is warming up..
        /// </summary>
        internal static string DeviceWarmingUp {
            get {
                return ResourceManager.GetString("DeviceWarmingUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission to save files at this location..
        /// </summary>
        internal static string DontHavePermission {
            get {
                return ResourceManager.GetString("DontHavePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download and Install.
        /// </summary>
        internal static string DownloadAndInstall {
            get {
                return ResourceManager.GetString("DownloadAndInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Error.
        /// </summary>
        internal static string DownloadError {
            get {
                return ResourceManager.GetString("DownloadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to send an email..
        /// </summary>
        internal static string EmailError {
            get {
                return ResourceManager.GetString("EmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email PDF Progress.
        /// </summary>
        internal static string EmailPdfProgress {
            get {
                return ResourceManager.GetString("EmailPdfProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want NAPS2 to automatically check for updates?.
        /// </summary>
        internal static string EnableAutoUpdates {
            get {
                return ResourceManager.GetString("EnableAutoUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when trying to save the file..
        /// </summary>
        internal static string ErrorSaving {
            get {
                return ResourceManager.GetString("ErrorSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated download size: {0} MB.
        /// </summary>
        internal static string EstimatedDownloadSize {
            get {
                return ResourceManager.GetString("EstimatedDownloadSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have unsaved changes. Are you sure you want to exit and discard those changes?.
        /// </summary>
        internal static string ExitWithUnsavedChanges {
            get {
                return ResourceManager.GetString("ExitWithUnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file could not be overwritten because it is currently in use..
        /// </summary>
        internal static string FileInUse {
            get {
                return ResourceManager.GetString("FileInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more files could not be downloaded..
        /// </summary>
        internal static string FilesCouldNotBeDownloaded {
            get {
                return ResourceManager.GetString("FilesCouldNotBeDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} / {1} files.
        /// </summary>
        internal static string FilesProgressFormat {
            get {
                return ResourceManager.GetString("FilesProgressFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files.
        /// </summary>
        internal static string FileTypeAllFiles {
            get {
                return ResourceManager.GetString("FileTypeAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitmap Files (*.bmp).
        /// </summary>
        internal static string FileTypeBmp {
            get {
                return ResourceManager.GetString("FileTypeBmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enhanced Windows MetaFile (*.emf).
        /// </summary>
        internal static string FileTypeEmf {
            get {
                return ResourceManager.GetString("FileTypeEmf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchangeable Image File (*.exif).
        /// </summary>
        internal static string FileTypeExif {
            get {
                return ResourceManager.GetString("FileTypeExif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIF File (*.gif).
        /// </summary>
        internal static string FileTypeGif {
            get {
                return ResourceManager.GetString("FileTypeGif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Files.
        /// </summary>
        internal static string FileTypeImageFiles {
            get {
                return ResourceManager.GetString("FileTypeImageFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JPEG File (*.jpg, *.jpeg).
        /// </summary>
        internal static string FileTypeJpeg {
            get {
                return ResourceManager.GetString("FileTypeJpeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF Document (*.pdf).
        /// </summary>
        internal static string FileTypePdf {
            get {
                return ResourceManager.GetString("FileTypePdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PNG File (*.png).
        /// </summary>
        internal static string FileTypePng {
            get {
                return ResourceManager.GetString("FileTypePng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIFF File (*.tiff, *.tif).
        /// </summary>
        internal static string FileTypeTiff {
            get {
                return ResourceManager.GetString("FileTypeTiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image saved..
        /// </summary>
        internal static string ImageSaved {
            get {
                return ResourceManager.GetString("ImageSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} images saved..
        /// </summary>
        internal static string ImagesSaved {
            get {
                return ResourceManager.GetString("ImagesSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; could not be imported..
        /// </summary>
        internal static string ImportErrorCouldNot {
            get {
                return ResourceManager.GetString("ImportErrorCouldNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; could not be imported. Only PDF files generated by NAPS2 can be imported..
        /// </summary>
        internal static string ImportErrorNAPS2Pdf {
            get {
                return ResourceManager.GetString("ImportErrorNAPS2Pdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing....
        /// </summary>
        internal static string Importing {
            get {
                return ResourceManager.GetString("Importing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing {0}....
        /// </summary>
        internal static string ImportingFormat {
            get {
                return ResourceManager.GetString("ImportingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Progress.
        /// </summary>
        internal static string ImportProgress {
            get {
                return ResourceManager.GetString("ImportProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation Complete.
        /// </summary>
        internal static string InstallComplete {
            get {
                return ResourceManager.GetString("InstallComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation complete. Do you want to restart NAPS2 now?.
        /// </summary>
        internal static string InstallCompletePromptRestart {
            get {
                return ResourceManager.GetString("InstallCompletePromptRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation failed..
        /// </summary>
        internal static string InstallFailed {
            get {
                return ResourceManager.GetString("InstallFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation Failed.
        /// </summary>
        internal static string InstallFailedTitle {
            get {
                return ResourceManager.GetString("InstallFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}x{2} {3}).
        /// </summary>
        internal static string NamedPageSizeFormat {
            get {
                return ResourceManager.GetString("NamedPageSizeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name missing..
        /// </summary>
        internal static string NameMissing {
            get {
                return ResourceManager.GetString("NameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAPS2.
        /// </summary>
        internal static string NAPS2 {
            get {
                return ResourceManager.GetString("NAPS2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No device selected..
        /// </summary>
        internal static string NoDeviceSelected {
            get {
                return ResourceManager.GetString("NoDeviceSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No scanning device was found..
        /// </summary>
        internal static string NoDevicesFound {
            get {
                return ResourceManager.GetString("NoDevicesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected scanner does not support using duplex. If your scanner is supposed to support duplex, try using a different driver..
        /// </summary>
        internal static string NoDuplexSupport {
            get {
                return ResourceManager.GetString("NoDuplexSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected scanner does not support using a feeder. If your scanner does have a feeder, try using a different driver..
        /// </summary>
        internal static string NoFeederSupport {
            get {
                return ResourceManager.GetString("NoFeederSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No pages are in the feeder..
        /// </summary>
        internal static string NoPagesInFeeder {
            get {
                return ResourceManager.GetString("NoPagesInFeeder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Now.
        /// </summary>
        internal static string NotNow {
            get {
                return ResourceManager.GetString("NotNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An update to OCR is available..
        /// </summary>
        internal static string OcrUpdateAvailable {
            get {
                return ResourceManager.GetString("OcrUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of {0}.
        /// </summary>
        internal static string OfN {
            get {
                return ResourceManager.GetString("OfN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite File.
        /// </summary>
        internal static string OverwriteFile {
            get {
                return ResourceManager.GetString("OverwriteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to copy content from the file &apos;{0}&apos;..
        /// </summary>
        internal static string PdfNoPermissionToExtractContent {
            get {
                return ResourceManager.GetString("PdfNoPermissionToExtractContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF saved..
        /// </summary>
        internal static string PdfSaved {
            get {
                return ResourceManager.GetString("PdfSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1}.
        /// </summary>
        internal static string PdfStatus {
            get {
                return ResourceManager.GetString("PdfStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} / {1}.
        /// </summary>
        internal static string ProgressFormat {
            get {
                return ResourceManager.GetString("ProgressFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovering....
        /// </summary>
        internal static string Recovering {
            get {
                return ResourceManager.GetString("Recovering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery Progress.
        /// </summary>
        internal static string RecoveryProgress {
            get {
                return ResourceManager.GetString("RecoveryProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Image.
        /// </summary>
        internal static string ResetImage {
            get {
                return ResourceManager.GetString("ResetImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Images Progress.
        /// </summary>
        internal static string SaveImagesProgress {
            get {
                return ResourceManager.GetString("SaveImagesProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save PDF Progress.
        /// </summary>
        internal static string SavePdfProgress {
            get {
                return ResourceManager.GetString("SavePdfProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving {0}....
        /// </summary>
        internal static string SavingFormat {
            get {
                return ResourceManager.GetString("SavingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan.
        /// </summary>
        internal static string Scan {
            get {
                return ResourceManager.GetString("Scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanned Image.
        /// </summary>
        internal static string ScannedImage {
            get {
                return ResourceManager.GetString("ScannedImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning page {0}.
        /// </summary>
        internal static string ScanPageProgress {
            get {
                return ResourceManager.GetString("ScanPageProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected ({0}).
        /// </summary>
        internal static string SelectedCount {
            get {
                return ResourceManager.GetString("SelectedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a profile before clicking Scan..
        /// </summary>
        internal static string SelectProfileBeforeScan {
            get {
                return ResourceManager.GetString("SelectProfileBeforeScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} / {1} MB.
        /// </summary>
        internal static string SizeProgress {
            get {
                return ResourceManager.GetString("SizeProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred with the scanning driver..
        /// </summary>
        internal static string UnknownDriverError {
            get {
                return ResourceManager.GetString("UnknownDriverError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved Changes.
        /// </summary>
        internal static string UnsavedChanges {
            get {
                return ResourceManager.GetString("UnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A newer version of NAPS2 is available. Do you want to update now?.
        /// </summary>
        internal static string UpdateNow {
            get {
                return ResourceManager.GetString("UpdateNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
