//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NAPS2.Lang.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SettingsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettingsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NAPS2.Lang.Resources.SettingsResources", typeof(SettingsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black &amp; White.
        /// </summary>
        internal static string BitDepth_1BlackAndWhite {
            get {
                return ResourceManager.GetString("BitDepth_1BlackAndWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24-bit Color.
        /// </summary>
        internal static string BitDepth_24Color {
            get {
                return ResourceManager.GetString("BitDepth_24Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grayscale.
        /// </summary>
        internal static string BitDepth_8Grayscale {
            get {
                return ResourceManager.GetString("BitDepth_8Grayscale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100 dpi.
        /// </summary>
        internal static string Dpi_100 {
            get {
                return ResourceManager.GetString("Dpi_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1200 dpi.
        /// </summary>
        internal static string Dpi_1200 {
            get {
                return ResourceManager.GetString("Dpi_1200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 150 dpi.
        /// </summary>
        internal static string Dpi_150 {
            get {
                return ResourceManager.GetString("Dpi_150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 200 dpi.
        /// </summary>
        internal static string Dpi_200 {
            get {
                return ResourceManager.GetString("Dpi_200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 300 dpi.
        /// </summary>
        internal static string Dpi_300 {
            get {
                return ResourceManager.GetString("Dpi_300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 600 dpi.
        /// </summary>
        internal static string Dpi_600 {
            get {
                return ResourceManager.GetString("Dpi_600", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        internal static string HorizontalAlign_Center {
            get {
                return ResourceManager.GetString("HorizontalAlign_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        internal static string HorizontalAlign_Left {
            get {
                return ResourceManager.GetString("HorizontalAlign_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        internal static string HorizontalAlign_Right {
            get {
                return ResourceManager.GetString("HorizontalAlign_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A3 (297x420 mm).
        /// </summary>
        internal static string PageSize_A3 {
            get {
                return ResourceManager.GetString("PageSize_A3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A4 (210x297 mm).
        /// </summary>
        internal static string PageSize_A4 {
            get {
                return ResourceManager.GetString("PageSize_A4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A5 (148x210 mm).
        /// </summary>
        internal static string PageSize_A5 {
            get {
                return ResourceManager.GetString("PageSize_A5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom....
        /// </summary>
        internal static string PageSize_Custom {
            get {
                return ResourceManager.GetString("PageSize_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US Legal (8.5x14 in).
        /// </summary>
        internal static string PageSize_Legal {
            get {
                return ResourceManager.GetString("PageSize_Legal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US Letter (8.5x11 in).
        /// </summary>
        internal static string PageSize_Letter {
            get {
                return ResourceManager.GetString("PageSize_Letter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cm.
        /// </summary>
        internal static string PageSizeUnit_Centimetre {
            get {
                return ResourceManager.GetString("PageSizeUnit_Centimetre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        internal static string PageSizeUnit_Inch {
            get {
                return ResourceManager.GetString("PageSizeUnit_Inch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mm.
        /// </summary>
        internal static string PageSizeUnit_Millimetre {
            get {
                return ResourceManager.GetString("PageSizeUnit_Millimetre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1:1.
        /// </summary>
        internal static string Scale_1_1 {
            get {
                return ResourceManager.GetString("Scale_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1:2.
        /// </summary>
        internal static string Scale_1_2 {
            get {
                return ResourceManager.GetString("Scale_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1:4.
        /// </summary>
        internal static string Scale_1_4 {
            get {
                return ResourceManager.GetString("Scale_1_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1:8.
        /// </summary>
        internal static string Scale_1_8 {
            get {
                return ResourceManager.GetString("Scale_1_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplex.
        /// </summary>
        internal static string Source_Duplex {
            get {
                return ResourceManager.GetString("Source_Duplex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feeder.
        /// </summary>
        internal static string Source_Feeder {
            get {
                return ResourceManager.GetString("Source_Feeder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glass.
        /// </summary>
        internal static string Source_Glass {
            get {
                return ResourceManager.GetString("Source_Glass", resourceCulture);
            }
        }
    }
}
