namespace NAPS2.Scan.Internal.Sane;

/// <summary>
/// Translations of option values used for matching against SANE, which doesn't provide non-localized
/// option values.
///
/// This isn't perfect as it doesn't fully account for historical/future translations or third-party
/// backends, but it's the best we can do for now.
/// </summary>
//
// Auto-generated by NAPS2.Tools.Localization.SaneOptsCommand.
// Run "n2 saneopts" to update.
internal static class SaneOptionTranslations {
    public static readonly string[] Color = {
        "Színes",
        "Кольоровий",
        "Barva",
        "Couleur",
        "Kleur",
        "Color",
        "彩色",
        "Färg",
        "Color",
        "Koloro",
        "Colore",
        "Color",
        "Farge",
        "Colour",
        "Color",
        "Farbe",
        "Farve",
        "צבע",
        "Цвят",
        "カラー",
        "Color",
        "Cor",
        "Kolor",
        "Cor",
        "Цветной",
        "Väri"
    };

    public static readonly string[] Gray = {
        "Szürke",
        "Сірий",
        "Šedá",
        "Gris",
        "Grijs",
        "Gris",
        "灰阶",
        "Grå",
        "Gray",
        "Grizo",
        "Grigio",
        "Gris",
        "Grå",
        "Grey",
        "Gris",
        "Graustufen",
        "Gråtone",
        "אפור",
        "Сиво",
        "グレー",
        "Gray",
        "Gris",
        "Skala szarości",
        "Cinzento",
        "Чёрно-белый",
        "Harmaasävy"
    };

    public static readonly string[] Lineart = {
        "Vonalas",
        "Штрихове",
        "Perokresba",
        "Trait",
        "Lijntekening",
        "Art lineal",
        "线稿",
        "Streckteckning",
        "Lineart",
        "Duuma",
        "Binario",
        "Línea de arte",
        "Strektegning",
        "Lineart",
        "Art lineal",
        "Strichzeichnung",
        "Stregtegning",
        "סגנון קווי",
        "Lineart",
        "線画",
        "Lineart",
        "Liña de arte",
        "Tryb kreski",
        "Linhas",
        "Штриховой",
        "Viivapiirros"
    };
}