//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NAPS2.Sdk.Tests {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ImageResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ImageResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("NAPS2.Sdk.Tests.ImageResources", typeof(ImageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] dog {
            get {
                object obj = ResourceManager.GetObject("dog", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] dog_bw {
            get {
                object obj = ResourceManager.GetObject("dog_bw", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] dog_bw_24bit {
            get {
                object obj = ResourceManager.GetObject("dog_bw_24bit", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] dog_bw_jpg {
            get {
                object obj = ResourceManager.GetObject("dog_bw_jpg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] dog_bw_bmp {
            get {
                object obj = ResourceManager.GetObject("dog_bw_bmp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] dog_bw_tiff {
            get {
                object obj = ResourceManager.GetObject("dog_bw_tiff", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] dog_bw_p300 {
            get {
                object obj = ResourceManager.GetObject("dog_bw_p300", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] dog_bw_invertpal {
            get {
                object obj = ResourceManager.GetObject("dog_bw_invertpal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] dog_b_n300 {
            get {
                object obj = ResourceManager.GetObject("dog_b_n300", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] dog_b_p300 {
            get {
                object obj = ResourceManager.GetObject("dog_b_p300", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] dog_c_5_10_15_20 {
            get {
                object obj = ResourceManager.GetObject("dog_c_5_10_15_20", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] dog_c_n300 {
            get {
                object obj = ResourceManager.GetObject("dog_c_n300", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] dog_c_p300 {
            get {
                object obj = ResourceManager.GetObject("dog_c_p300", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] dog_h_n300 {
            get {
                object obj = ResourceManager.GetObject("dog_h_n300", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] dog_h_p300 {
            get {
                object obj = ResourceManager.GetObject("dog_h_p300", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] dog_r_180 {
            get {
                object obj = ResourceManager.GetObject("dog_r_180", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] dog_r_n45 {
            get {
                object obj = ResourceManager.GetObject("dog_r_n45", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] dog_r_p46 {
            get {
                object obj = ResourceManager.GetObject("dog_r_p46", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] dog_r_p90 {
            get {
                object obj = ResourceManager.GetObject("dog_r_p90", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] dog_sc_50pct {
            get {
                object obj = ResourceManager.GetObject("dog_sc_50pct", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] dog_sh_n1000 {
            get {
                object obj = ResourceManager.GetObject("dog_sh_n1000", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] dog_sh_p1000 {
            get {
                object obj = ResourceManager.GetObject("dog_sh_p1000", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] dog_s_n300 {
            get {
                object obj = ResourceManager.GetObject("dog_s_n300", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] dog_s_p300 {
            get {
                object obj = ResourceManager.GetObject("dog_s_p300", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] dog_thumb_256 {
            get {
                object obj = ResourceManager.GetObject("dog_thumb_256", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] deskewed {
            get {
                object obj = ResourceManager.GetObject("deskewed", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] skewed {
            get {
                object obj = ResourceManager.GetObject("skewed", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] skewed_bw {
            get {
                object obj = ResourceManager.GetObject("skewed_bw", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] stock_cat {
            get {
                object obj = ResourceManager.GetObject("stock_cat", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] dog_b_p300_thumb_256 {
            get {
                object obj = ResourceManager.GetObject("dog_b_p300_thumb_256", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] patcht {
            get {
                object obj = ResourceManager.GetObject("patcht", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ocr_test {
            get {
                object obj = ResourceManager.GetObject("ocr_test", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] image_upc_barcode {
            get {
                object obj = ResourceManager.GetObject("image_upc_barcode", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] dog_low_quality {
            get {
                object obj = ResourceManager.GetObject("dog_low_quality", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] dog_alpha {
            get {
                object obj = ResourceManager.GetObject("dog_alpha", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] dog_alpha_tiff {
            get {
                object obj = ResourceManager.GetObject("dog_alpha_tiff", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] dog_mask {
            get {
                object obj = ResourceManager.GetObject("dog_mask", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] dog_jp2 {
            get {
                object obj = ResourceManager.GetObject("dog_jp2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] dog_png {
            get {
                object obj = ResourceManager.GetObject("dog_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] dog_bmp {
            get {
                object obj = ResourceManager.GetObject("dog_bmp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] dog_tiff {
            get {
                object obj = ResourceManager.GetObject("dog_tiff", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] dog_huge {
            get {
                object obj = ResourceManager.GetObject("dog_huge", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] dog_huge_png {
            get {
                object obj = ResourceManager.GetObject("dog_huge_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] animals_tiff {
            get {
                object obj = ResourceManager.GetObject("animals_tiff", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] dog_clustered_gray {
            get {
                object obj = ResourceManager.GetObject("dog_clustered_gray", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] dog_gray {
            get {
                object obj = ResourceManager.GetObject("dog_gray", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] dog_gray_png {
            get {
                object obj = ResourceManager.GetObject("dog_gray_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] dog_gray_24bit_png {
            get {
                object obj = ResourceManager.GetObject("dog_gray_24bit_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] dog_gray_bmp {
            get {
                object obj = ResourceManager.GetObject("dog_gray_bmp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] dog_gray_tiff {
            get {
                object obj = ResourceManager.GetObject("dog_gray_tiff", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] dog_gray_24bit_tiff {
            get {
                object obj = ResourceManager.GetObject("dog_gray_24bit_tiff", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
