//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NAPS2.Sdk.Tests {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PdfResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PdfResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("NAPS2.Sdk.Tests.PdfResources", typeof(PdfResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] word_generated_pdf {
            get {
                object obj = ResourceManager.GetObject("word_generated_pdf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] word_p1 {
            get {
                object obj = ResourceManager.GetObject("word_p1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] word_p2 {
            get {
                object obj = ResourceManager.GetObject("word_p2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] word_p1_rotated {
            get {
                object obj = ResourceManager.GetObject("word_p1_rotated", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] word_p2_bw {
            get {
                object obj = ResourceManager.GetObject("word_p2_bw", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] image_pdf {
            get {
                object obj = ResourceManager.GetObject("image_pdf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] image_with_text_pdf {
            get {
                object obj = ResourceManager.GetObject("image_with_text_pdf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] image_pdf_bw {
            get {
                object obj = ResourceManager.GetObject("image_pdf_bw", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] word_patcht_pdf {
            get {
                object obj = ResourceManager.GetObject("word_patcht_pdf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] word_patcht_p1 {
            get {
                object obj = ResourceManager.GetObject("word_patcht_p1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] encrypted_pdf {
            get {
                object obj = ResourceManager.GetObject("encrypted_pdf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] image_pdf_png {
            get {
                object obj = ResourceManager.GetObject("image_pdf_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
