//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NAPS2.Console.Lang.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConsoleResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConsoleResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NAPS2.Console.Lang.Resources.ConsoleResources", typeof(ConsoleResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attaching {0}....
        /// </summary>
        internal static string Attaching {
            get {
                return ResourceManager.GetString("Attaching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attaching the previously exported PDF....
        /// </summary>
        internal static string AttachingExportedPDF {
            get {
                return ResourceManager.GetString("AttachingExportedPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginning scan....
        /// </summary>
        internal static string BeginningScan {
            get {
                return ResourceManager.GetString("BeginningScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The encryption configuration file could not be loaded..
        /// </summary>
        internal static string CouldntLoadEncryptionConfig {
            get {
                return ResourceManager.GetString("CouldntLoadEncryptionConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission to save files at this location..
        /// </summary>
        internal static string DontHavePermission {
            get {
                return ResourceManager.GetString("DontHavePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emailing....
        /// </summary>
        internal static string Emailing {
            get {
                return ResourceManager.GetString("Emailing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email not sent..
        /// </summary>
        internal static string EmailNotSent {
            get {
                return ResourceManager.GetString("EmailNotSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email successfully sent..
        /// </summary>
        internal static string EmailSent {
            get {
                return ResourceManager.GetString("EmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when trying to delete a temporary directory..
        /// </summary>
        internal static string ErrorDeletingTempDir {
            get {
                return ResourceManager.GetString("ErrorDeletingTempDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error importing file. Path: {0}.
        /// </summary>
        internal static string ErrorImporting {
            get {
                return ResourceManager.GetString("ErrorImporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exported page {0} of {1}..
        /// </summary>
        internal static string ExportedPage {
            get {
                return ResourceManager.GetString("ExportedPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting....
        /// </summary>
        internal static string Exporting {
            get {
                return ResourceManager.GetString("Exporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting images for use as an attachment....
        /// </summary>
        internal static string ExportingImagesToAttach {
            get {
                return ResourceManager.GetString("ExportingImagesToAttach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting PDF for use as an attachment....
        /// </summary>
        internal static string ExportingPDFToAttach {
            get {
                return ResourceManager.GetString("ExportingPDFToAttach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File already exists. Use --force to overwrite. Path: {0}.
        /// </summary>
        internal static string FileAlreadyExists {
            get {
                return ResourceManager.GetString("FileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished saving images to {0}.
        /// </summary>
        internal static string FinishedSavingImages {
            get {
                return ResourceManager.GetString("FinishedSavingImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imported file {0} of {1}..
        /// </summary>
        internal static string ImportedFile {
            get {
                return ResourceManager.GetString("ImportedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing....
        /// </summary>
        internal static string Importing {
            get {
                return ResourceManager.GetString("Importing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAPS2.
        /// </summary>
        internal static string NAPS2 {
            get {
                return ResourceManager.GetString("NAPS2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No scanned pages to email..
        /// </summary>
        internal static string NoPagesToEmail {
            get {
                return ResourceManager.GetString("NoPagesToEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No scanned pages to export..
        /// </summary>
        internal static string NoPagesToExport {
            get {
                return ResourceManager.GetString("NoPagesToExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one of the -o/--output or -e/--email options must be specified..
        /// </summary>
        internal static string OutputOrEmailRequired {
            get {
                return ResourceManager.GetString("OutputOrEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwriting: {0}.
        /// </summary>
        internal static string Overwriting {
            get {
                return ResourceManager.GetString("Overwriting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} page(s) scanned..
        /// </summary>
        internal static string PagesScanned {
            get {
                return ResourceManager.GetString("PagesScanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified profile is unavailable or ambiguous.\r\nUse the --profile option to specify a profile by name..
        /// </summary>
        internal static string ProfileUnavailableOrAmbiguous {
            get {
                return ResourceManager.GetString("ProfileUnavailableOrAmbiguous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanned Image.
        /// </summary>
        internal static string ScannedImage {
            get {
                return ResourceManager.GetString("ScannedImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending email....
        /// </summary>
        internal static string SendingEmail {
            get {
                return ResourceManager.GetString("SendingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting scan {0} of {1}....
        /// </summary>
        internal static string StartingScan {
            get {
                return ResourceManager.GetString("StartingScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully saved PDF file to {0}.
        /// </summary>
        internal static string SuccessfullySavedPdf {
            get {
                return ResourceManager.GetString("SuccessfullySavedPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred..
        /// </summary>
        internal static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting {0}ms....
        /// </summary>
        internal static string Waiting {
            get {
                return ResourceManager.GetString("Waiting", resourceCulture);
            }
        }
    }
}
