//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NAPS2.Lang.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MiscResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MiscResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NAPS2.Lang.Resources.MiscResources", typeof(MiscResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic Updates.
        /// </summary>
        internal static string AutoUpdates {
            get {
                return ResourceManager.GetString("AutoUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Profile.
        /// </summary>
        internal static string ChooseProfile {
            get {
                return ResourceManager.GetString("ChooseProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to clear {0} item(s)?.
        /// </summary>
        internal static string ConfirmClearItems {
            get {
                return ResourceManager.GetString("ConfirmClearItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete {0} item(s)?.
        /// </summary>
        internal static string ConfirmDeleteItems {
            get {
                return ResourceManager.GetString("ConfirmDeleteItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete {0} profiles?.
        /// </summary>
        internal static string ConfirmDeleteMultipleProfiles {
            get {
                return ResourceManager.GetString("ConfirmDeleteMultipleProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the profile {0}?.
        /// </summary>
        internal static string ConfirmDeleteSingleProfile {
            get {
                return ResourceManager.GetString("ConfirmDeleteSingleProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file {0} already exists. Do you want to overwrite it?.
        /// </summary>
        internal static string ConfirmOverwriteFile {
            get {
                return ResourceManager.GetString("ConfirmOverwriteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected scanner could not be found..
        /// </summary>
        internal static string DeviceNotFound {
            get {
                return ResourceManager.GetString("DeviceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected scanner is offline..
        /// </summary>
        internal static string DeviceOffline {
            get {
                return ResourceManager.GetString("DeviceOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission to save files at this location..
        /// </summary>
        internal static string DontHavePermission {
            get {
                return ResourceManager.GetString("DontHavePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download and Install.
        /// </summary>
        internal static string DownloadAndInstall {
            get {
                return ResourceManager.GetString("DownloadAndInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to send an email..
        /// </summary>
        internal static string EmailError {
            get {
                return ResourceManager.GetString("EmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want NAPS2 to automatically check for updates?.
        /// </summary>
        internal static string EnableAutoUpdates {
            get {
                return ResourceManager.GetString("EnableAutoUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitmap Files (*.bmp).
        /// </summary>
        internal static string FileTypeBmp {
            get {
                return ResourceManager.GetString("FileTypeBmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enhanced Windows MetaFile (*.emf).
        /// </summary>
        internal static string FileTypeEmf {
            get {
                return ResourceManager.GetString("FileTypeEmf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchangeable Image File (*.exif).
        /// </summary>
        internal static string FileTypeExif {
            get {
                return ResourceManager.GetString("FileTypeExif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIF File (*.gif).
        /// </summary>
        internal static string FileTypeGif {
            get {
                return ResourceManager.GetString("FileTypeGif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JPEG File (*.jpg, *.jpeg).
        /// </summary>
        internal static string FileTypeJpeg {
            get {
                return ResourceManager.GetString("FileTypeJpeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF document (*.pdf).
        /// </summary>
        internal static string FileTypePdf {
            get {
                return ResourceManager.GetString("FileTypePdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PNG File (*.png).
        /// </summary>
        internal static string FileTypePng {
            get {
                return ResourceManager.GetString("FileTypePng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIFF File (*.tiff, *.tif).
        /// </summary>
        internal static string FileTypeTiff {
            get {
                return ResourceManager.GetString("FileTypeTiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation Complete.
        /// </summary>
        internal static string InstallComplete {
            get {
                return ResourceManager.GetString("InstallComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation complete. Do you want to restart NAPS2 now?.
        /// </summary>
        internal static string InstallCompletePromptRestart {
            get {
                return ResourceManager.GetString("InstallCompletePromptRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation failed..
        /// </summary>
        internal static string InstallFailed {
            get {
                return ResourceManager.GetString("InstallFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation Failed.
        /// </summary>
        internal static string InstallFailedTitle {
            get {
                return ResourceManager.GetString("InstallFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name missing..
        /// </summary>
        internal static string NameMissing {
            get {
                return ResourceManager.GetString("NameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAPS2.
        /// </summary>
        internal static string NAPS2 {
            get {
                return ResourceManager.GetString("NAPS2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No device selected..
        /// </summary>
        internal static string NoDeviceSelected {
            get {
                return ResourceManager.GetString("NoDeviceSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No scanning device was found..
        /// </summary>
        internal static string NoDevicesFound {
            get {
                return ResourceManager.GetString("NoDevicesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Now.
        /// </summary>
        internal static string NotNow {
            get {
                return ResourceManager.GetString("NotNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite File.
        /// </summary>
        internal static string OverwriteFile {
            get {
                return ResourceManager.GetString("OverwriteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1}.
        /// </summary>
        internal static string PdfStatus {
            get {
                return ResourceManager.GetString("PdfStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanned Image.
        /// </summary>
        internal static string ScannedImage {
            get {
                return ResourceManager.GetString("ScannedImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a profile before clicking Scan..
        /// </summary>
        internal static string SelectProfileBeforeScan {
            get {
                return ResourceManager.GetString("SelectProfileBeforeScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred with the scanning driver..
        /// </summary>
        internal static string UnknownDriverError {
            get {
                return ResourceManager.GetString("UnknownDriverError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A newer version of NAPS2 is available. Do you want to update now?.
        /// </summary>
        internal static string UpdateNow {
            get {
                return ResourceManager.GetString("UpdateNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
