//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NAPS2.Lang.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UiStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UiStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NAPS2.Lang.Resources.UiStrings", typeof(UiStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string AboutFormTitle {
            get {
                return ResourceManager.GetString("AboutFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternate Deinterleave.
        /// </summary>
        internal static string AltDeinterleave {
            get {
                return ResourceManager.GetString("AltDeinterleave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternate Interleave.
        /// </summary>
        internal static string AltInterleave {
            get {
                return ResourceManager.GetString("AltInterleave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apple Driver.
        /// </summary>
        internal static string AppleDriver {
            get {
                return ResourceManager.GetString("AppleDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Save Settings.
        /// </summary>
        internal static string AutoSaveSettings {
            get {
                return ResourceManager.GetString("AutoSaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Scan.
        /// </summary>
        internal static string BatchScan {
            get {
                return ResourceManager.GetString("BatchScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bit depth:.
        /// </summary>
        internal static string BitDepthLabel {
            get {
                return ResourceManager.GetString("BitDepthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black and White.
        /// </summary>
        internal static string BlackAndWhite {
            get {
                return ResourceManager.GetString("BlackAndWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brightness / Contrast.
        /// </summary>
        internal static string BrightnessContrast {
            get {
                return ResourceManager.GetString("BrightnessContrast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brightness:.
        /// </summary>
        internal static string BrightnessLabel {
            get {
                return ResourceManager.GetString("BrightnessLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        internal static string CheckForUpdates {
            get {
                return ResourceManager.GetString("CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose device.
        /// </summary>
        internal static string ChooseDevice {
            get {
                return ResourceManager.GetString("ChooseDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear All.
        /// </summary>
        internal static string ClearAll {
            get {
                return ResourceManager.GetString("ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrast:.
        /// </summary>
        internal static string ContrastLabel {
            get {
                return ResourceManager.GetString("ContrastLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright 2009, 2012-2020 NAPS2 Contributors.
        /// </summary>
        internal static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop.
        /// </summary>
        internal static string Crop {
            get {
                return ResourceManager.GetString("Crop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Rotation.
        /// </summary>
        internal static string CustomRotation {
            get {
                return ResourceManager.GetString("CustomRotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deinterleave.
        /// </summary>
        internal static string Deinterleave {
            get {
                return ResourceManager.GetString("Deinterleave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deskew.
        /// </summary>
        internal static string Deskew {
            get {
                return ResourceManager.GetString("Deskew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device:.
        /// </summary>
        internal static string DeviceLabel {
            get {
                return ResourceManager.GetString("DeviceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name:.
        /// </summary>
        internal static string DisplayNameLabel {
            get {
                return ResourceManager.GetString("DisplayNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        internal static string Donate {
            get {
                return ResourceManager.GetString("Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Settings.
        /// </summary>
        internal static string EditProfileFormTitle {
            get {
                return ResourceManager.GetString("EditProfileFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email All as PDF.
        /// </summary>
        internal static string EmailAllAsPdf {
            get {
                return ResourceManager.GetString("EmailAllAsPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email PDF.
        /// </summary>
        internal static string EmailPdf {
            get {
                return ResourceManager.GetString("EmailPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Selected as PDF.
        /// </summary>
        internal static string EmailSelectedAsPdf {
            get {
                return ResourceManager.GetString("EmailSelectedAsPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Settings.
        /// </summary>
        internal static string EmailSettings {
            get {
                return ResourceManager.GetString("EmailSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Auto Save.
        /// </summary>
        internal static string EnableAutoSave {
            get {
                return ResourceManager.GetString("EnableAutoSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flip.
        /// </summary>
        internal static string Flip {
            get {
                return ResourceManager.GetString("Flip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal align:.
        /// </summary>
        internal static string HorizontalAlignLabel {
            get {
                return ResourceManager.GetString("HorizontalAlignLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hue / Saturation.
        /// </summary>
        internal static string HueSaturation {
            get {
                return ResourceManager.GetString("HueSaturation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icons from:.
        /// </summary>
        internal static string IconsFrom {
            get {
                return ResourceManager.GetString("IconsFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Settings.
        /// </summary>
        internal static string ImageSettings {
            get {
                return ResourceManager.GetString("ImageSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interleave.
        /// </summary>
        internal static string Interleave {
            get {
                return ResourceManager.GetString("Interleave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Down.
        /// </summary>
        internal static string MoveDown {
            get {
                return ResourceManager.GetString("MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Up.
        /// </summary>
        internal static string MoveUp {
            get {
                return ResourceManager.GetString("MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Profile.
        /// </summary>
        internal static string NewProfile {
            get {
                return ResourceManager.GetString("NewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCR.
        /// </summary>
        internal static string Ocr {
            get {
                return ResourceManager.GetString("Ocr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page size:.
        /// </summary>
        internal static string PageSizeLabel {
            get {
                return ResourceManager.GetString("PageSizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paper source:.
        /// </summary>
        internal static string PaperSourceLabel {
            get {
                return ResourceManager.GetString("PaperSourceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF Settings.
        /// </summary>
        internal static string PdfSettings {
            get {
                return ResourceManager.GetString("PdfSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles.
        /// </summary>
        internal static string Profiles {
            get {
                return ResourceManager.GetString("Profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles.
        /// </summary>
        internal static string ProfilesFormTitle {
            get {
                return ResourceManager.GetString("ProfilesFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reorder.
        /// </summary>
        internal static string Reorder {
            get {
                return ResourceManager.GetString("Reorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution:.
        /// </summary>
        internal static string ResolutionLabel {
            get {
                return ResourceManager.GetString("ResolutionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse.
        /// </summary>
        internal static string Reverse {
            get {
                return ResourceManager.GetString("Reverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate.
        /// </summary>
        internal static string Rotate {
            get {
                return ResourceManager.GetString("Rotate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate Left.
        /// </summary>
        internal static string RotateLeft {
            get {
                return ResourceManager.GetString("RotateLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate Right.
        /// </summary>
        internal static string RotateRight {
            get {
                return ResourceManager.GetString("RotateRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SANE Driver.
        /// </summary>
        internal static string SaneDriver {
            get {
                return ResourceManager.GetString("SaneDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save All as Images.
        /// </summary>
        internal static string SaveAllAsImages {
            get {
                return ResourceManager.GetString("SaveAllAsImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save All as PDF.
        /// </summary>
        internal static string SaveAllAsPdf {
            get {
                return ResourceManager.GetString("SaveAllAsPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Images.
        /// </summary>
        internal static string SaveImages {
            get {
                return ResourceManager.GetString("SaveImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save PDF.
        /// </summary>
        internal static string SavePdf {
            get {
                return ResourceManager.GetString("SavePdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Selected as Images.
        /// </summary>
        internal static string SaveSelectedAsImages {
            get {
                return ResourceManager.GetString("SaveSelectedAsImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Selected as PDF.
        /// </summary>
        internal static string SaveSelectedAsPdf {
            get {
                return ResourceManager.GetString("SaveSelectedAsPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale:.
        /// </summary>
        internal static string ScaleLabel {
            get {
                return ResourceManager.GetString("ScaleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan.
        /// </summary>
        internal static string Scan {
            get {
                return ResourceManager.GetString("Scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Default.
        /// </summary>
        internal static string SetDefault {
            get {
                return ResourceManager.GetString("SetDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharpen.
        /// </summary>
        internal static string Sharpen {
            get {
                return ResourceManager.GetString("Sharpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TWAIN Driver.
        /// </summary>
        internal static string TwainDriver {
            get {
                return ResourceManager.GetString("TwainDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use native UI.
        /// </summary>
        internal static string UseNativeUi {
            get {
                return ResourceManager.GetString("UseNativeUi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use predefined settings.
        /// </summary>
        internal static string UsePredefinedSettings {
            get {
                return ResourceManager.GetString("UsePredefinedSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WIA Driver.
        /// </summary>
        internal static string WiaDriver {
            get {
                return ResourceManager.GetString("WiaDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        internal static string Zoom {
            get {
                return ResourceManager.GetString("Zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom In.
        /// </summary>
        internal static string ZoomIn {
            get {
                return ResourceManager.GetString("ZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom Out.
        /// </summary>
        internal static string ZoomOut {
            get {
                return ResourceManager.GetString("ZoomOut", resourceCulture);
            }
        }
    }
}
