//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NAPS2 {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Icons {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Icons() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("NAPS2.Icons", typeof(Icons).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] arrow_down {
            get {
                object obj = ResourceManager.GetObject("arrow_down", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] arrow_out {
            get {
                object obj = ResourceManager.GetObject("arrow_out", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] arrow_rotate_anticlockwise {
            get {
                object obj = ResourceManager.GetObject("arrow_rotate_anticlockwise", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] arrow_rotate_clockwise {
            get {
                object obj = ResourceManager.GetObject("arrow_rotate_clockwise", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] arrow_switch {
            get {
                object obj = ResourceManager.GetObject("arrow_switch", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] arrow_up {
            get {
                object obj = ResourceManager.GetObject("arrow_up", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] blueprints {
            get {
                object obj = ResourceManager.GetObject("blueprints", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] cross {
            get {
                object obj = ResourceManager.GetObject("cross", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] key_small {
            get {
                object obj = ResourceManager.GetObject("key_small", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] email_small {
            get {
                object obj = ResourceManager.GetObject("email_small", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] email_attach {
            get {
                object obj = ResourceManager.GetObject("email_attach", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] file_extension_pdf {
            get {
                object obj = ResourceManager.GetObject("file_extension_pdf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] file_extension_pdf_small {
            get {
                object obj = ResourceManager.GetObject("file_extension_pdf_small", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] information {
            get {
                object obj = ResourceManager.GetObject("information", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] info_rhombus {
            get {
                object obj = ResourceManager.GetObject("info_rhombus", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] pdf_email {
            get {
                object obj = ResourceManager.GetObject("pdf_email", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] picture {
            get {
                object obj = ResourceManager.GetObject("picture", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] scanner_16 {
            get {
                object obj = ResourceManager.GetObject("scanner_16", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] scanner_32 {
            get {
                object obj = ResourceManager.GetObject("scanner_32", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] scanner_48_old {
            get {
                object obj = ResourceManager.GetObject("scanner_48_old", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] scanner_48 {
            get {
                object obj = ResourceManager.GetObject("scanner_48", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] scanner_64 {
            get {
                object obj = ResourceManager.GetObject("scanner_64", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] scanner_128 {
            get {
                object obj = ResourceManager.GetObject("scanner_128", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] scanner_default {
            get {
                object obj = ResourceManager.GetObject("scanner_default", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] scanner_lock_default {
            get {
                object obj = ResourceManager.GetObject("scanner_lock_default", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] scanner_lock {
            get {
                object obj = ResourceManager.GetObject("scanner_lock", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] transform_flip {
            get {
                object obj = ResourceManager.GetObject("transform_flip", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] zoom_actual {
            get {
                object obj = ResourceManager.GetObject("zoom_actual", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] zoom_in {
            get {
                object obj = ResourceManager.GetObject("zoom_in", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] zoom_out {
            get {
                object obj = ResourceManager.GetObject("zoom_out", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] accept {
            get {
                object obj = ResourceManager.GetObject("accept", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] accept_small {
            get {
                object obj = ResourceManager.GetObject("accept_small", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] add_small {
            get {
                object obj = ResourceManager.GetObject("add_small", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] cancel {
            get {
                object obj = ResourceManager.GetObject("cancel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] cancel_small {
            get {
                object obj = ResourceManager.GetObject("cancel_small", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] cross_small {
            get {
                object obj = ResourceManager.GetObject("cross_small", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] pencil {
            get {
                object obj = ResourceManager.GetObject("pencil", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] pencil_small {
            get {
                object obj = ResourceManager.GetObject("pencil_small", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] tick {
            get {
                object obj = ResourceManager.GetObject("tick", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] tick_small {
            get {
                object obj = ResourceManager.GetObject("tick_small", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] blueprints_small {
            get {
                object obj = ResourceManager.GetObject("blueprints_small", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] world {
            get {
                object obj = ResourceManager.GetObject("world", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] folder_picture {
            get {
                object obj = ResourceManager.GetObject("folder_picture", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] arrow_refresh {
            get {
                object obj = ResourceManager.GetObject("arrow_refresh", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] arrow_rotate_anticlockwise_small {
            get {
                object obj = ResourceManager.GetObject("arrow_rotate_anticlockwise_small", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] arrow_rotate_clockwise_small {
            get {
                object obj = ResourceManager.GetObject("arrow_rotate_clockwise_small", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] arrow_switch_small {
            get {
                object obj = ResourceManager.GetObject("arrow_switch_small", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] text {
            get {
                object obj = ResourceManager.GetObject("text", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] text_small {
            get {
                object obj = ResourceManager.GetObject("text_small", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] control_play_blue {
            get {
                object obj = ResourceManager.GetObject("control_play_blue", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] control_play_blue_small {
            get {
                object obj = ResourceManager.GetObject("control_play_blue_small", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] color_wheel {
            get {
                object obj = ResourceManager.GetObject("color_wheel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] contrast {
            get {
                object obj = ResourceManager.GetObject("contrast", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] image_edit {
            get {
                object obj = ResourceManager.GetObject("image_edit", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] transform_crop {
            get {
                object obj = ResourceManager.GetObject("transform_crop", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] weather_sun {
            get {
                object obj = ResourceManager.GetObject("weather_sun", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] arrow_down_small {
            get {
                object obj = ResourceManager.GetObject("arrow_down_small", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] arrow_up_small {
            get {
                object obj = ResourceManager.GetObject("arrow_up_small", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] pictures {
            get {
                object obj = ResourceManager.GetObject("pictures", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] picture_edit {
            get {
                object obj = ResourceManager.GetObject("picture_edit", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] picture_save {
            get {
                object obj = ResourceManager.GetObject("picture_save", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] arrow_left {
            get {
                object obj = ResourceManager.GetObject("arrow_left", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] arrow_right {
            get {
                object obj = ResourceManager.GetObject("arrow_right", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] printer {
            get {
                object obj = ResourceManager.GetObject("printer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] application_cascade {
            get {
                object obj = ResourceManager.GetObject("application_cascade", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] close {
            get {
                object obj = ResourceManager.GetObject("close", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] picture_small {
            get {
                object obj = ResourceManager.GetObject("picture_small", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] color_gradient {
            get {
                object obj = ResourceManager.GetObject("color_gradient", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] color_management {
            get {
                object obj = ResourceManager.GetObject("color_management", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] contrast_high {
            get {
                object obj = ResourceManager.GetObject("contrast_high", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] contrast_with_sun {
            get {
                object obj = ResourceManager.GetObject("contrast_with_sun", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] sharpen {
            get {
                object obj = ResourceManager.GetObject("sharpen", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] btn_donate_LG {
            get {
                object obj = ResourceManager.GetObject("btn_donate_LG", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] gmail {
            get {
                object obj = ResourceManager.GetObject("gmail", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] outlookweb {
            get {
                object obj = ResourceManager.GetObject("outlookweb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] thunderbird {
            get {
                object obj = ResourceManager.GetObject("thunderbird", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] apple_mail {
            get {
                object obj = ResourceManager.GetObject("apple_mail", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] email_setting {
            get {
                object obj = ResourceManager.GetObject("email_setting", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] mail_yellow {
            get {
                object obj = ResourceManager.GetObject("mail_yellow", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] hourglass_grey {
            get {
                object obj = ResourceManager.GetObject("hourglass_grey", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] wireless16 {
            get {
                object obj = ResourceManager.GetObject("wireless16", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] cog {
            get {
                object obj = ResourceManager.GetObject("cog", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] cog_small {
            get {
                object obj = ResourceManager.GetObject("cog_small", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] information_small {
            get {
                object obj = ResourceManager.GetObject("information_small", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] favicon {
            get {
                object obj = ResourceManager.GetObject("favicon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] exclamation {
            get {
                object obj = ResourceManager.GetObject("exclamation", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] diskette {
            get {
                object obj = ResourceManager.GetObject("diskette", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] zoom {
            get {
                object obj = ResourceManager.GetObject("zoom", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] zoom_small {
            get {
                object obj = ResourceManager.GetObject("zoom_small", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
