//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NAPS2.WinForms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FBlackWhite {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FBlackWhite() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NAPS2.WinForms.FBlackWhite", typeof(FBlackWhite).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Top, Bottom, Left, Right.
        /// </summary>
        internal static System.Windows.Forms.AnchorStyles pictureBox_Anchor {
            get {
                object obj = ResourceManager.GetObject("pictureBox.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=12,Y=12}.
        /// </summary>
        internal static System.Drawing.Point pictureBox_Location {
            get {
                object obj = ResourceManager.GetObject("pictureBox.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=296, Height=179}.
        /// </summary>
        internal static System.Drawing.Size pictureBox_Size {
            get {
                object obj = ResourceManager.GetObject("pictureBox.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.PictureBoxSizeMode similar to Zoom.
        /// </summary>
        internal static System.Windows.Forms.PictureBoxSizeMode pictureBox_SizeMode {
            get {
                object obj = ResourceManager.GetObject("pictureBox.SizeMode", resourceCulture);
                return ((System.Windows.Forms.PictureBoxSizeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 0.
        /// </summary>
        internal static int pictureBox_TabIndex {
            get {
                object obj = ResourceManager.GetObject("pictureBox.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Bottom, Left, Right.
        /// </summary>
        internal static System.Windows.Forms.AnchorStyles tbThreshold_Anchor {
            get {
                object obj = ResourceManager.GetObject("tbThreshold.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        internal static System.Windows.Forms.ImeMode tbThreshold_ImeMode {
            get {
                object obj = ResourceManager.GetObject("tbThreshold.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=12,Y=197}.
        /// </summary>
        internal static System.Drawing.Point tbThreshold_Location {
            get {
                object obj = ResourceManager.GetObject("tbThreshold.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=252, Height=45}.
        /// </summary>
        internal static System.Drawing.Size tbThreshold_Size {
            get {
                object obj = ResourceManager.GetObject("tbThreshold.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 1.
        /// </summary>
        internal static int tbThreshold_TabIndex {
            get {
                object obj = ResourceManager.GetObject("tbThreshold.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Bottom, Right.
        /// </summary>
        internal static System.Windows.Forms.AnchorStyles txtThreshold_Anchor {
            get {
                object obj = ResourceManager.GetObject("txtThreshold.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=270,Y=197}.
        /// </summary>
        internal static System.Drawing.Point txtThreshold_Location {
            get {
                object obj = ResourceManager.GetObject("txtThreshold.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=38, Height=20}.
        /// </summary>
        internal static System.Drawing.Size txtThreshold_Size {
            get {
                object obj = ResourceManager.GetObject("txtThreshold.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 2.
        /// </summary>
        internal static int txtThreshold_TabIndex {
            get {
                object obj = ResourceManager.GetObject("txtThreshold.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string txtThreshold_Text {
            get {
                return ResourceManager.GetString("txtThreshold.Text", resourceCulture);
            }
        }
    }
}
